name: caffe_app_user
description: Caffe application that allows table orders by scanning the QR code.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_nav_bar: ^5.0.6
  mobile_scanner: ^3.2.0
  qr_code_scanner: ^1.0.1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_database: ^10.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - images/
    - lang/en.json
    - lang/hr.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "images/background.png"
  adaptive_icon_foreground: "images/foreground.png"